#!/bin/bash

cd ${0%/*} || exit 1
set -x

# if [ -f $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments ]
# then  . $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
# fi

wmake libraries/numericalMethods
wmake libraries/parabolicVelocity

wmake solvers/biofilmFoam2D
wmake solvers/biofilmFoam3D

wmake utilities/biomass
wmake utilities/sessileBiomass
wmake utilities/inoculumGenerator
wmake utilities/permeability
