#!/bin/bash

. $WM_PROJECT_DIR/bin/tools/RunFunctions

app=biofilmFoam2D

cp 0/M.org 0/M
runApplication blockMesh
runApplication inoculumGenerator -patch z0 -nbcells 6
runApplication topoSet
runApplication setFields
runApplication $app
